source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
target 'QJYRouter' do
    pod 'RAMRouter', :path => '../'# :git => 'https://github.com/RamboQiu/RAMRouter.git'#, :branch => 'dev'
  	#pod 'RAMUtil', :git => 'https://github.com/RamboQiu/RAMUtil.git', :subspecs => ['RAMLog'], :tag => '1.0.0'
end

