source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
target 'QJYRouter' do
    pod 'RAMRouter', :path => '/Users/qiujunyun/Documents/WorkSpace/github/RAMRouter'#, :branch => 'dev'
end

